# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimedia import QMediaPlayer
from PyQt5.QtMultimediaWidgets import QVideoWidget


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 650)
        Dialog.setMinimumSize(QtCore.QSize(900, 650))
        Dialog.setMaximumSize(QtCore.QSize(900, 650))
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 70, 209, 461))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.Ara = QtWidgets.QPushButton(self.formLayoutWidget)
        self.Ara.setMinimumSize(QtCore.QSize(40, 40))
        self.Ara.setMaximumSize(QtCore.QSize(40, 40))
        self.Ara.setObjectName("Ara")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Ara)
        self.ara = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.ara.setMinimumSize(QtCore.QSize(0, 30))
        self.ara.setMaximumSize(QtCore.QSize(16777215, 40))
        self.ara.setObjectName("ara")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ara)
        self.Kategori = QtWidgets.QComboBox(self.formLayoutWidget)
        self.Kategori.setMinimumSize(QtCore.QSize(0, 30))
        self.Kategori.setObjectName("Kategori")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.Kategori)
        self.kelimeler = QtWidgets.QListWidget(self.formLayoutWidget)
        self.kelimeler.setEnabled(True)
        self.kelimeler.setMinimumSize(QtCore.QSize(0, 300))
        self.kelimeler.setMaximumSize(QtCore.QSize(16777215, 300))
        self.kelimeler.setObjectName("kelimeler")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.kelimeler)
        self.yardim = QtWidgets.QPushButton(self.formLayoutWidget)
        self.yardim.setMinimumSize(QtCore.QSize(0, 30))
        self.yardim.setMaximumSize(QtCore.QSize(16777215, 30))
        self.yardim.setSizeIncrement(QtCore.QSize(0, 40))
        self.yardim.setObjectName("yardim")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.yardim)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        ##Dialog.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Dialog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        
        self.statusbar = QtWidgets.QStatusBar(Dialog)
        self.statusbar.setObjectName("statusbar")
        
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 70, 421, 241))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayoutWidget.setMaximumSize(QtCore.QSize(650,450))
        self.horizontalLayoutWidget.setMinimumSize(QtCore.QSize(650,450))
        self.layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.layout.setContentsMargins(100, 0, 0, 0)
        self.layout.setObjectName("layout")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Ara.setText(_translate("Dialog", "Ara"))
        self.yardim.setText(_translate("Dialog", "YARDIM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
